### ISSUE TITLE
Implement monster taking a bite out of the runner

### ISSUE THREAD

**Issue by louie-mansour** [louie-mm/monster-dash#16]
At the moment the monster can run past the runner.

We need to implement a feature where the monster cannot run past the user but instead stays in the same spot as the user.

After the monster has reached the same spot as the user, it should play an audio clip to indicate that it has taken a bite out of the user.
Further to this, the monster will re-enter a ramp up stage (similar to at the start of the game) giving the user the chance to gain more distance ahead of the monster until it reaches full speed again

**Comment by FiddlinBill** [comment]
Ouch!

**Comment by louie-mansour** [comment]
Done
